version: '3'
services:
  
  back:
    image: node:18
    container_name: back
    build:
      context: ./back
      dockerfile: Dockerfile.back
    environment:
      NODE_ENV: development
    ports:
      - "3001:3001"
    networks:
      - webgateway

  front:
    image: node:14
    container_name: front
    build: 
      context: ./front
      dockerfile: Dockerfile.front
    ports:
      - "3000:3000"
    networks:
      - webgateway

networks:
  webgateway:
    driver: bridge