version: '3'
services:
  
  back:
    image: node:18
    container_name: back
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "3001:3001"
    networks:
      - my-network

  front:
    image: node:18
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
